#! /bin/sh

sxhkd &

feh --bg-fill ~/Pictures/mountains-during-sunset-1920×1080.jpg

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         1
# bspc config window_gap         12
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a GeoGebra desktop='^9' state=tiled follow=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Inkscape desktop='^7' state=tiled follow=on
bspc rule -a Emacs desktop='^2' state=tiled follow=on
bspc rule -a obsidian desktop='^6' state=tiled follow=on
# bspc rule -a XTerm desktop='^5' state=floating follow=on rectangle=1800x900+190+250
bspc rule -a URxvt desktop='^0' state=floating follow=on rectangle=1800x900+190+250
bspc rule -a Zathura state=tiled follow=on 

# ~/.config/bspwm/bspwmrc
#! /bin/sh

# bspc config border_width        1
# bspc config window_gap          0

# bspc config split_ratio         0.5
# bspc config borderless_monocle  true
# bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focused_border_color "#363636"
bspc config normal_border_color "#222222"
bspc config urgent_border_color "#ff0000"
bspc config focus_follows_pointer true

bspc config bottom_padding 0

xset s 300
xrdb ~/.Xdefaults
urxvtd -q -f -o
synclient tapbutton1=0 tapbutton2=0 tapbutton3=0 verttwofingerscroll=0 vertedgescroll=1 horizedgescroll=1 horizscrolldelta=10

##config for lemonbar(panel)
bash ~/.config/lemonbar/lemonbar.sh &
