#! /bin/sh

# Add doomemacs package to the PATH
# export PATH=$PATH:$HOME/.config/emacs/bin

pgrep -x sxhkd > /dev/null || sxhkd &
fcitx5 &

# if [[ $(xrandr -q | grep -w 'DP1 connected') ]]; then
# 	xrandr --output eDP1 --primary --mode 2160x1440 --rotate normal --output DP1 --mode 1920x1080 --rotate normal --right-of eDP1
# 	bspc monitor DP1 -d 1 2 3 4
# 	bspc monitor eDP1 -d V VI VII VIII IX X
# else
# 	bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0
# fi

$HOME/.scripts/switchMonitor.sh &
# feh --bg-fill ~/Pictures/MIT.webp

# bspc monitor -d 1 2 3 4 5 6 7 8 9 0
# $HOME/.config/polybar/launch.sh &

bspc config border_width        1
bspc config window_gap          4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a firefox desktop='^3' state=tiled follow=on
bspc rule -a GeoGebra desktop='^9' state=tiled follow=on
bspc rule -a Gimp desktop='^7' follow=on
bspc rule -a Inkscape desktop='^7' follow=on
bspc rule -a Emacs desktop='^2' state=tiled follow=on
bspc rule -a obsidian desktop='^5' state=tiled follow=on
bspc rule -a URxvt desktop='^0' state=floating follow=on rectangle=1800x900+190+250
bspc rule -a Zathura state=tiled follow=on 
bspc rule -a feh state=floating follow=on 
bspc rule -a XTerm state=floating follow=on 

bspc config focus_by_distance   true
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"
bspc config focus_follows_pointer true

bspc config bottom_padding 0

xmodmap .Xmodmap
xinput set-prop 11 "libinput Tapping Enabled" 1
xsetwacom set 14 Button 2 "key +ctrl +shift p -shift -ctrl"
xsetwacom set 15 Button 2 "key +ctrl +shift p -shift -ctrl"
xrandr --dpi 100
xrdb -merge .Xresources

